In [17]:
import numpy as np

In [18]:
np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
np.zeros((2, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [20]:
np.ones((4, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.empty((2, 2))

array([[2.12199579e-314, 1.05038792e-311],
       [3.02368175e-321, 3.79442416e-321]])

In [22]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
np.arange(2, 21 , 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [24]:
np.linspace(0, 20, num=5)   

array([ 0.,  5., 10., 15., 20.])

In [25]:
x = np.ones(5, dtype=np.int64)
x

array([1, 1, 1, 1, 1], dtype=int64)

In [26]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [29]:
arr_example = np.array([[[0, 1, 2, 3],
                        [4, 5, 6, 7]],
                        [[0, 1, 2, 3],
                        [4, 5, 6, 7]],
                        [[0 ,1 ,2, 3],
                        [4, 5, 6, 7]]])
print(arr_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [30]:
arr_example.ndim    # number of dimensions of the array

3

In [31]:
arr_example.size    # number of elements in the array

24

In [32]:
arr_example.shape   # shape of the array

(3, 2, 4)